# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11i_9a77mouR_l_P2ahF1bx3D2pyNRvTm
"""

# Streamlit app for HouseWorthAI (Real Estate Price Estimator)
# Full ML pipeline with retro neon dark theme similar to MLmadeEasy

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Page config and custom CSS
st.set_page_config(page_title="HouseWorthAI", layout="wide")
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Press+Start+2P&family=VT323&display=swap');
    * {
        font-family: 'VT323', monospace;
        letter-spacing: 1px;
    }
    .main {
        background: #000000;
        color: white;
    }
    h1, h2, h3, h4 {
        color: #ff00ff;
        text-shadow: 0 0 5px #ff00ff, 0 0 10px #ff00ff;
    }
    .stButton>button {
        background: black;
        color: #ff00ff;
        border: 2px solid #ff00ff;
        font-family: 'Press Start 2P', cursive;
    }
    .stTextInput>div>div>input, .stSelectbox>div>div>select {
        background: #000000;
        color: white;
        border: 2px solid #ff00ff;
    }
    </style>
""", unsafe_allow_html=True)

st.title("🏠 HouseWorthAI")
st.markdown("""
<div style="color: #00ffff; font-size: 20px;">
    Predict Real Estate Prices with Style 🚀
</div>
""", unsafe_allow_html=True)

# Sidebar options
st.sidebar.header("1. Upload Dataset")
uploaded_file = st.sidebar.file_uploader("Upload a CSV file with real estate data", type=["csv"])

if uploaded_file:
    df = pd.read_csv(uploaded_file)
    st.subheader("📄 Preview of Dataset")
    st.dataframe(df.head(), use_container_width=True)

    # Preprocessing
    st.sidebar.header("2. Preprocessing")
    if st.sidebar.checkbox("✅ Handle Missing Values", True):
        df.fillna(df.mean(numeric_only=True), inplace=True)

    cat_cols = df.select_dtypes(include='object').columns.tolist()
    if st.sidebar.checkbox("🔤 Encode Categorical Features", True) and cat_cols:
        le = LabelEncoder()
        for col in cat_cols:
            df[col] = le.fit_transform(df[col])

    # Feature selection
    st.sidebar.header("3. Feature Engineering")
    target = st.sidebar.selectbox("🎯 Select target column (e.g., price)", df.columns)
    features = st.sidebar.multiselect("🛠️ Select feature columns", [col for col in df.columns if col != target], default=[col for col in df.columns if col != target])

    if features and target:
        X = df[features]
        y = df[target]

        # Train/test split
        st.sidebar.header("4. Split Data")
        test_size = st.sidebar.slider("📊 Test size", 0.1, 0.5, 0.2)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=42)

        # Scale features
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_test_scaled = scaler.transform(X_test)

        # Model selection
        st.sidebar.header("5. Train Model")
        model_type = st.sidebar.selectbox("🤖 Choose model", ["Linear Regression", "Random Forest"])

        if model_type == "Linear Regression":
            model = LinearRegression()
        else:
            model = RandomForestRegressor(n_estimators=100, random_state=42)

        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)

        # Evaluation
        st.subheader("📈 Model Evaluation")
        st.markdown(f"**R² Score:** :sparkles: {r2_score(y_test, y_pred):.4f}")
        st.markdown(f"**RMSE:** :zap: {np.sqrt(mean_squared_error(y_test, y_pred)):.4f}")

        # Visualization
        st.subheader("📊 Actual vs Predicted Prices")
        result_df = pd.DataFrame({"Actual": y_test, "Predicted": y_pred})
        fig = px.scatter(result_df, x="Actual", y="Predicted", trendline="ols", labels={"x": "Actual Price", "y": "Predicted Price"}, template="plotly_dark")
        st.plotly_chart(fig, use_container_width=True)

        # Download predictions
        st.subheader("💾 Download Predictions")
        st.download_button("📥 Download CSV", result_df.to_csv(index=False), "predictions.csv", "text/csv")

else:
    st.info("🧾 Please upload a dataset to get started.")